# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userinfo_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('movieInfo', models.TextField()),
                ('star', models.IntegerField(default=0)),
                ('quote', models.TextField()),
            ],
        ),
    ]
