# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_movieinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterInfo',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('uid', models.IntegerField(default=0)),
                ('des', models.TextField()),
                ('img', models.TextField()),
                ('info', models.TextField()),
                ('isVip', models.BooleanField(default=False)),
                ('weiBo', models.TextField()),
                ('zhiHu', models.TextField()),
            ],
        ),
    ]
