# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_masterinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterinfo',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
