# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_masterinfo_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterArticle',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('uid', models.IntegerField(default=0)),
                ('des', models.TextField()),
                ('article_title', models.IntegerField()),
                ('article_address', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='masterinfo',
            name='des',
        ),
        migrations.RemoveField(
            model_name='masterinfo',
            name='weiBo',
        ),
        migrations.RemoveField(
            model_name='masterinfo',
            name='zhiHu',
        ),
        migrations.AddField(
            model_name='masterinfo',
            name='blog',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
