# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20170417_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterarticle',
            name='name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='masterarticle',
            name='nick_name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='masterinfo',
            name='nick_name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
