# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-13 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('pic', models.IntegerField(default=1000)),
                ('address', models.CharField(max_length=250)),
                ('des', models.CharField(max_length=1000)),
            ],
        ),
    ]
