# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-13 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='pic',
            field=models.CharField(max_length=1000),
        ),
    ]
